name: Generate ASCII at work
on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: List Repo Files
          uses: ls -ltra
        
        - name: Execute Shell Script
          run: |
            chmod +x asci-script.s
            ./asci-script.sh

        


        

        
